name: Update GSI Feed

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 安定版を指定

      - name: Install dependencies
        # beautifulsoup4 を追加
        run: pip install curl_cffi beautifulsoup4

      - name: Fetch and Fix RDF
        run: python update_feed.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 拡張子を .xml に変更
          git add gsi_updates.xml
          if ! git diff --cached --exit-code; then
            git commit -m "Update and repair GSI feed"
            git push
          else
            echo "No changes detected."
          fi
